import { LoaderConfig } from './types';

export const DEFAULT_GRID_SIZE = 4;

export const PRESETS: Partial<LoaderConfig>[] = [
  {
    name: 'X-Style Pulse',
    activeCells: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    color: '#ffffff',
    speed: 1.2,
    shape: 'circle',
    animationStyle: 'wave',
    glow: 0,
    gridSize: 4,
    blur: 0,
  },
  {
    name: 'Matrix Rain',
    activeCells: [1, 5, 9, 13, 2, 6, 10, 14],
    color: '#00ff41',
    speed: 2,
    shape: 'square',
    animationStyle: 'matrix',
    glow: 1,
    blur: 0,
  },
  {
    name: 'Cyber Dot',
    activeCells: [0, 2, 8, 10, 5, 15],
    color: '#ff00ff',
    speed: 3,
    shape: 'dot',
    animationStyle: 'glow',
    glow: 1,
    blur: 2,
  },
  {
    name: 'Neon Wave',
    activeCells: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    color: '#00d2ff',
    speed: 1.5,
    shape: 'rounded',
    animationStyle: 'wave',
    glow: 1,
    blur: 1,
  },
  {
    name: 'Floating Ghost',
    activeCells: [5, 6, 9, 10],
    color: '#a855f7',
    speed: 1,
    shape: 'circle',
    animationStyle: 'float',
    glow: 1,
    blur: 1,
  },
  {
    name: 'Thinking',
    activeCells: [5, 6, 9, 10],
    color: '#22c55e',
    speed: 1.5,
    shape: 'rounded',
    animationStyle: 'pulse',
    glow: 1,
    blur: 0,
  },
  {
    name: 'Reading Docs',
    activeCells: [1, 2, 4, 7, 8, 11, 13, 14],
    color: '#ef4444',
    speed: 2,
    shape: 'circle',
    animationStyle: 'scale',
    glow: 1,
    blur: 0,
  },
  {
    name: 'Analysing',
    activeCells: [0, 3, 12, 15],
    color: '#3b82f6',
    speed: 1,
    shape: 'square',
    animationStyle: 'glow',
    glow: 1,
    blur: 0,
  },
  {
    name: 'Debugging',
    activeCells: [0, 1, 2, 4, 5, 8],
    color: '#0ea5e9',
    speed: 1.2,
    shape: 'rounded',
    animationStyle: 'opacity',
    glow: 0,
    blur: 0,
  },
  {
    name: 'Retro Cross',
    activeCells: [1, 4, 5, 6, 9, 13, 14],
    color: '#00ffff',
    speed: 1,
    shape: 'square',
    animationStyle: 'pixel',
    glow: 0,
    blur: 0,
  }
];

export const INITIAL_CONFIG: LoaderConfig = {
  id: 'custom-1',
  name: 'My Custom Loader',
  gridSize: 4,
  activeCells: [5, 6, 9, 10],
  color: '#3b82f6',
  speed: 1,
  shape: 'rounded',
  animationStyle: 'pulse',
  backgroundStyle: 'static',
  glow: 1,
  blur: 0,
};
